from direct.interval.Interval import Interval
from panda3d.core import NodePath, Point3

class Actor(NodePath):
    def __init__(self, models: str, anims: dict[str, str] = dict()) -> None: ...
    def posInterval(self, t: float, pt: Point3) -> Interval: ...
    def cleanup(self) -> Interval: ...
