class NodePath:
    def reparentTo(self, other: "NodePath") -> None: ...
    def attachNewNode(self, node: "PandaNode") -> "NodePath": ...

class PandaNode:
    pass

class Point3:
    def __init__(self, x: float, y: float, z: float): ...
