class NodePath:
    def reparentTo(self, other: "NodePath") -> None: ...
    def attachNewNode(self, node: "PandaNode") -> "NodePath": ...
    def getChild(self, n: int) -> "NodePath": ...
    def setScale(self, scale: float) -> "NodePath": ...
    def setPos(self, x: float, y: float, z: float) -> "NodePath": ...
    def removeNode(self) -> None: ...

class PandaNode:
    def removeNode(self) -> None: ...

class Point3:
    def __init__(self, x: float, y: float, z: float) -> None: ...
